/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.user.form.register.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.user.form.register.service.persistence.UserFormRegisterPK;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserFormRegister service. Represents a row in the &quot;User_UserFormRegister&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.user.form.register.model.impl.UserFormRegisterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.user.form.register.model.impl.UserFormRegisterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserFormRegister
 * @generated
 */
@ProviderType
public interface UserFormRegisterModel extends BaseModel<UserFormRegister> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user form register model instance should use the {@link UserFormRegister} interface instead.
	 */

	/**
	 * Returns the primary key of this user form register.
	 *
	 * @return the primary key of this user form register
	 */
	public UserFormRegisterPK getPrimaryKey();

	/**
	 * Sets the primary key of this user form register.
	 *
	 * @param primaryKey the primary key of this user form register
	 */
	public void setPrimaryKey(UserFormRegisterPK primaryKey);

	/**
	 * Returns the uuid of this user form register.
	 *
	 * @return the uuid of this user form register
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user form register.
	 *
	 * @param uuid the uuid of this user form register
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user form register ID of this user form register.
	 *
	 * @return the user form register ID of this user form register
	 */
	public long getUserFormRegisterId();

	/**
	 * Sets the user form register ID of this user form register.
	 *
	 * @param userFormRegisterId the user form register ID of this user form register
	 */
	public void setUserFormRegisterId(long userFormRegisterId);

	/**
	 * Returns the group ID of this user form register.
	 *
	 * @return the group ID of this user form register
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user form register.
	 *
	 * @param groupId the group ID of this user form register
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this user form register.
	 *
	 * @return the create date of this user form register
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user form register.
	 *
	 * @param createDate the create date of this user form register
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the name of this user form register.
	 *
	 * @return the name of this user form register
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user form register.
	 *
	 * @param name the name of this user form register
	 */
	public void setName(String name);

	/**
	 * Returns the surname of this user form register.
	 *
	 * @return the surname of this user form register
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this user form register.
	 *
	 * @param surname the surname of this user form register
	 */
	public void setSurname(String surname);

	/**
	 * Returns the email of this user form register.
	 *
	 * @return the email of this user form register
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this user form register.
	 *
	 * @param email the email of this user form register
	 */
	public void setEmail(String email);

	/**
	 * Returns the birthday of this user form register.
	 *
	 * @return the birthday of this user form register
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this user form register.
	 *
	 * @param birthday the birthday of this user form register
	 */
	public void setBirthday(Date birthday);

}