/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.user.form.register.model.impl;

import com.liferay.user.form.register.model.UserFormRegister;
import com.liferay.user.form.register.service.UserFormRegisterLocalServiceUtil;

/**
 * The extended model base implementation for the UserFormRegister service. Represents a row in the &quot;User_UserFormRegister&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserFormRegisterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserFormRegisterImpl
 * @see UserFormRegister
 * @generated
 */
public abstract class UserFormRegisterBaseImpl
	extends UserFormRegisterModelImpl implements UserFormRegister {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user form register model instance should use the <code>UserFormRegister</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UserFormRegisterLocalServiceUtil.addUserFormRegister(this);
		}
		else {
			UserFormRegisterLocalServiceUtil.updateUserFormRegister(this);
		}
	}

}